x-read-database: &x-read-database
  path: /databases/{uuid}
  method: GET

x-alias-uuid-to-id: &x-alias-uuid-to-id
  uuid: id

x-alias-env-name-to-name: &x-alias-env-name-to-name
  environment_name: name

x-alias-env-uuid-to-uuid: &x-alias-env-uuid-to-uuid
  env_uuid: uuid

x-delete-database: &x-delete-database
  path: /databases/{uuid}
  method: DELETE


provider:
  name: coolify

resources:
  postgresql_database:
    create:
      path: /databases/postgresql
      method: POST
    read:
      <<: *x-read-database
    delete:
      <<: *x-delete-database
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  redis_database:
    create:
      path: /databases/redis
      method: POST
    read:
      <<: *x-read-database
    delete:
      <<: *x-delete-database
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  mysql_database:
    create:
      path: /databases/mysql
      method: POST
    read:
      <<: *x-read-database
    delete:
      <<: *x-delete-database
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  mongodb_database:
    create:
      path: /databases/mongodb
      method: POST
    read:
      <<: *x-read-database
    delete:
      <<: *x-delete-database
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  keydb_database:
    create:
      path: /databases/keydb
      method: POST
    read:
      <<: *x-read-database
    delete:
      <<: *x-delete-database
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  clickhouse_database:
    create:
      path: /databases/clickhouse
      method: POST
    read:
      <<: *x-read-database
    delete:
      <<: *x-delete-database
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  dragonfly_database:
    create:
      path: /databases/dragonfly
      method: POST
    read:
      <<: *x-read-database
    delete:
      <<: *x-delete-database
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  mariadb_database:
    create:
      path: /databases/mariadb
      method: POST
    read:
      <<: *x-read-database
    delete:
      <<: *x-delete-database
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  private_key:
    create:
      path: /security/keys
      method: POST
    read:
      path: /security/keys/{uuid}
      method: GET
    update:
      path: /security/keys/{uuid}
      method: PATCH
    delete:
      path: /security/keys/{uuid}
      method: DELETE
  server:
    create:
      path: /servers
      method: POST
    read:
      path: /servers/{uuid}
      method: GET
    update:
      path: /servers/{uuid}
      method: PATCH
    delete:
      path: /servers/{uuid}
      method: DELETE
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  project:
    create:
      path: /projects
      method: POST
    read:
      path: /projects/{uuid}
      method: GET
    update:
      path: /projects/{uuid}
      method: PATCH
    delete:
      path: /projects/{uuid}
      method: DELETE
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  application_envs:
    create:
      path: /applications/{uuid}/envs
      method: POST
    read:
      path: /applications/{uuid}/envs
      method: GET
    update:
      path: /applications/{uuid}/envs/bulk
      method: PATCH
    delete:
      path: /applications/{uuid}/envs/{env_uuid}
      method: DELETE
  service:
    create:
      path: /services
      method: POST
    read:
      path: /services/{uuid}
      method: GET
    delete:
      path: /services/{uuid}
      method: DELETE
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id
  service_env:
    create:
      path: /services/{uuid}/envs
      method: POST
    read:
      path: /services/{uuid}/envs/{env_uuid}
      method: GET
    schema:
      attributes:
        aliases:
          <<: *x-alias-uuid-to-id

data_sources:
  private_keys:
    read:
      path: /security/keys
      method: GET
  private_key:
    read:
      path: /security/keys/{uuid}
      method: GET
  teams:
    read:
      path: /teams
      method: GET
  team:
    read:
      path: /teams/{id}
      method: GET
  server:
    read:
      path: /servers/{uuid}
      method: GET
  servers:
    read:
      path: /servers
      method: GET
  server_resources:
    read:
      path: /servers/{uuid}/resources
      method: GET
  server_domains:
    read:
      path: /servers/{uuid}/domains
      method: GET
  project:
    read:
      path: /projects/{uuid}
      method: GET
  projects:
    read:
      path: /projects
      method: GET
  application:
    read:
      path: /applications/{uuid}
      method: GET
